### ISSUE TITLE
Unable to run the application - 

### ISSUE THREAD

**Issue by psharepoint10** [rlondner/okta-msoidc-sample#1]
Thanks for sample, I am using server 2012 R2, VS2013, .net 4.5 version. 
as instructed I have install all dependency, and added newly build Microsoft.Owin.Security.OpenIdConnect.dll in codeFlow Solution and tried running the application, getting error "CS1617: Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default"
in Web.Confing added Compilcation version to 4.0 and target to 4.5

<system.web>
    < compilation debug="true" targetFramework="4.0"  /> 
    < httpRuntime targetFramework="4.5"  />
  </system.web>

![image](https://cloud.githubusercontent.com/assets/28532244/25802250/820f70fe-33bf-11e7-9fcb-3c7b567fc57b.png)

Any help appreciated

**Comment by rlondner** [comment]
Hi @psharepoint10, please take a look at the most up-to-date version, hosted at https://github.com/oktadeveloper/okta-oauth-aspnet-codeflow. I will retire this repo once I get confirmation that you have received this response. Thank you and good luck!
